name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: JDK 17 beallitasa
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Maven build
      run: mvn clean package
    
    - name: JAR mentese
      uses: actions/upload-artifact@v4
      with:
        name: spring-app
        path: target/*.jar
