name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./nyeuni

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven (skip checkstyle)
      run: mvn clean package -Dcheckstyle.skip=true

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: nyeuni/target/*.jar
